### PR TITLE
Update README files

### PR DESCRIPTION
**Pull request by tortuetorche**
@MathieuDoyon I can't directly push to your repository (error 403), so I send you this pull request...

### CODE REVIEW

**Comment by tortuetorche** [comment]
Thank you for the merge :+1:

**Comment by MathieuDoyon** [comment]
That's weird, you should have access to. 
screenshot_2015-03-14-08-57-32

**Comment by tortuetorche** [comment]
Look at the `repositories` counter it's at `0`.

**Comment by tortuetorche** [comment]
Here an example:
contributors_repositories

**Comment by tortuetorche** [comment]
I'm now a collaborator! :+1:

**Pull request merged**
